
platform :ios, '12.0'

target 'StuChef' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StuChef

  target 'StuChefTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StuChefUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'
pod 'FirebaseUI/Auth'
